---
project_name: "ToCare"
hostname: "toCare.lo"
hostnames: []
forwarded_ports: {
    "80": "8080",    # HTTP
    "443": "8443",   # HTTPS
    "3000": "3000",  # BrowserSync default port
}

box_ip: "10.10.10.16"
box_name: "drifter/stretch64-base"
box_url: "https://vagrantbox-public.liip.ch/drifter-stretch64-base.json"

database_name: "tocare"
root_directory: "/vagrant/"

python_version:  "3"
pip_version: "19.0.3"
pip_requirements: "requirements/dev.txt"
